### ISSUE TITLE
I want to record my weight so that I can keep track of the changes to it

### ISSUE THREAD

**Issue by senhongo** [senhongo/cleric#1]
## Tasks
- [ ] a page to enter weight and body/fat ratio
- [ ] date should automatically be set to todays date but can be changed by the user
- [ ] data should be saved into Firebase
