### ISSUE TITLE
I want to see the records against the a calendar

### ISSUE THREAD

**Issue by senhongo** [senhongo/cleric#3]
## Description

To better understand the fluctuations over a specific length of time, to see trends, to see when I've been skiving off.

## Tasks
- [x] create a calendar component
- [ ] create a daily view expands the data for that day
- [ ] think about how to display `activity` data
- [ ] data formatter

We don't have `diet` data so we'll doo that in #4

**Comment by senhongo** [comment]
A prototype `Calendar` component is ready. I haven't decided one the shape of the data yet. It could be an array of arrays (months[] / days[]) or and object of arrays ( month: days[])

**Comment by senhongo** [comment]
This might be a good opportunity to get to know the `Temporal` API

**Comment by senhongo** [comment]
## Presentation

- calendar format showing current month
- arrows for scrolling to previous months
- clicking on a day brings up a modal showing more details
- able to edit values when in details

## Stretch goals

Show previous month

**Comment by senhongo** [comment]
## Data analysis

- probably no time for trend lines
- display difference with last known data
